services:
  filebeat:
    image: elastic/filebeat:8.15.5
    container_name: filebeat
    user: root
    volumes:  # Какие данные копируем с локальной машины в контейнер!
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - registry:/usr/share/filebeat/data:rw
      - /var/log/kern.log:/var/log/kern.log:rw
    command: ["filebeat", "-e", "--strict.perms=false"]
#    command: ["filebeat", "--strict.perms=false"]
    restart: unless-stopped

volumes:
  registry:
